---
author: "Théo Lassale"
editor_options: 
  chunk_output_type: console
date: '`r Sys.Date()`'
output:
  html_document:
  theme: flatly
toc: true
toc_float: true
code_folding: hide
---


# **6. ROMA **{.tabset .tabset-fade .tabset-pills}


```{r import counts_gmt}
dge_filtered_roma <- cbind(dge_filtered$counts, dge_filtered$genes)
dge_filtered_roma <- dge_filtered_roma %>% relocate(genes, .before= "1_MTX1_3h")
rownames(dge_filtered_roma) <- make.names(dge_filtered_roma$genes, unique=TRUE)
dge_filtered_roma <- dge_filtered_roma %>% dplyr::select(-genes)
dge_filtered_roma_new <- cpm(dge_filtered_roma, log=TRUE)
dge_filtered_roma_df <- dge_filtered_roma_new %>% as.data.frame()
go_bp_genesymbols <- ReadGMTFile("/data/kdi_prod/.kdi/project_workspace_0/1929/acl/01.00/go_bp_genesymbol.gmt/")
```


```{r get_load_roma_results}
get_load_roma_results <- function(time, no_drug1, no_drug2, filen){
  # MTX
  dge_filtered_roma_df <- dge_filtered_roma_df %>% dplyr::select(contains(time) & !contains(no_drug1) & !contains(no_drug2))
  dge_filtered_roma_df <- dge_filtered_roma_df[, c(4,5,6,1,2,3)]
  roma_output <- readRDS(filen)
}
```

```{r get_shited_modules}
get_shifted_modules <- function(filen3, filen4, filen5, filen6, filen7){
  
  # Load roma output
  roma_output <- readRDS(filen3)
  rownames(roma_output$ModuleMatrix) <- gsub("GOBP_", "", rownames(roma_output$ModuleMatrix))
  rownames(roma_output$SampleMatrix) <- gsub("GOBP_", "", rownames(roma_output$SampleMatrix))
  
  # Get shifted modules
  shifted_modules_all <- roma_output$ModuleMatrix %>% as.data.frame() %>% dplyr::filter(`ppv Median Exp`<= 0.05) %>% rownames_to_column("shifted_modules") %>% dplyr::arrange(`ppv Median Exp`, desc(abs(`Median Exp`)))
  write(shifted_modules_all, filen4)
  
  # Get shifted modules (index for plot)
  shifted.modules <- which(roma_output$ModuleMatrix[,"ppv Median Exp"] <= 0.05)
  
  # Get top 20 shifted modules + Save them
  shifted_modules_top_20 <- roma_output$ModuleMatrix %>% as.data.frame() %>% dplyr::filter(`ppv Median Exp`<= 0.05) %>% rownames_to_column("shifted_modules") %>% dplyr::arrange(`ppv Median Exp`, desc(abs(`Median Exp`))) %>% dplyr::slice(1:20)
  write.csv(shifted_modules_top_20, filen5)
  
  # Plot activity scores of top 20 shifted modules
  png(filen6, width=1000, height=502)
  Plot.Genesets.Samples(roma_output, Selected = shifted.modules[shifted_modules_top_20$shifted_modules], cluster_cols = TRUE)
  dev.off()
  
  # Get intersection between BP and shifted modules
  shifted_modules_lower <- tolower(shifted_modules$shifted_modules)
  enriched_go_terms <- read.csv(filen7)
  intersect_roma_go <- intersect(shifted_modules_lower, enriched_go_terms$Description)
  intersect_roma_go_df <- intersect_roma_go %>% as.data.frame()
  colnames(intersect_roma_go_df) <- "intersection_BP_shifted"
  write.csv(intersect_roma_go_df, filen8)
}
```


```{r get_overdispersed_modules}
get_overdispersed_modules <- function(filen3, filen4, filen5, filen6, filen7, filen8, filen9){
  
  # Load roma output
  roma_output <- readRDS(filen3)
  rownames(roma_output$ModuleMatrix) <- gsub("GOBP_", "", rownames(roma_output$ModuleMatrix))
  rownames(roma_output$SampleMatrix) <- gsub("GOBP_", "", rownames(roma_output$SampleMatrix))
  
  # Get overdispersed modules
  overdispersed_modules_all <- roma_output$ModuleMatrix %>% as.data.frame() %>% dplyr::filter(`ppv L1`<= 0.05 & `ppv Median Exp` > 0.05) %>% rownames_to_column("overdispersed_modules") %>% dplyr::arrange(`ppv L1`, desc(`L1`))
  write.csv(overdispersed_modules_all, filen4)
  
  # Get overdispersed modules (index for plot)
  overdispersed.modules <- which(roma_output$ModuleMatrix[,"ppv L1"] <= 0.05)

  # Get top 20 overdispersed modules + Save them
  overdispersed_modules_top_20 <- roma_output$ModuleMatrix %>% as.data.frame() %>% dplyr::filter(`ppv L1`<= 0.05) %>% rownames_to_column("overdispersed_modules") %>% dplyr::arrange(`ppv L1`, desc(`L1`)) %>% dplyr::slice(1:20)
  write.csv(overdispersed_modules_top_20, filen5)
  
  # Plot activity scores of top 20 overdispersed modules
  png(filen6, width=1000, height=502)
  Plot.Genesets.Samples(roma_output, Selected = overdispersed.modules[overdispersed_modules_top_20$overdispersed_modules], cluster_cols = TRUE)
  dev.off()

  # Get top contributing genes (top 30) to activity score of overdispersed pathways
  for (i in 1:20){
    add_graph_number <- paste0(unlist(strsplit(filen7, ".png")), "_", i, ".png")
    png(add_graph_number, width=1000, height=502)
    PlotGeneWeight(RomaData = roma_output, PlotGenes = 30, LogExpression = FALSE, 
                   Selected = overdispersed.modules[overdispersed_modules_top_20$overdispersed_modules[i]])
    dev.off()
    }
  
  
  # Get intersection between BP and overdispersed
  overdispersed_modules_lower <- tolower(overdispersed_modules_all$overdispersed_modules)
  enriched_go_terms <- read.csv(filen8)
  intersect_roma_go <- intersect(overdispersed_modules_lower, enriched_go_terms$Description)
  intersect_roma_go_df <- intersect_roma_go %>% as.data.frame()
  colnames(intersect_roma_go_df) <- "intersection_BP_overdispersed"
  write.csv(intersect_roma_go_df, filen9)

}
```